name: GitHub Scrape Results Manual Deploy

on:  
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ manual-page-deploy ]
  schedule:
    - cron: '0 0,12 * * *' # runs every 12h

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.6'
      - name: Setup Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r _data/requirements.txt  
      - name: Scrape GitHub
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd _data
          python scrape_github.py
      - name: Build the website 
        run:  bundle exec jekyll build --baseurl /unitaryhack
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _site 
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}